# Generated by Django 4.0.1 on 2023-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Member email')),
                ('title', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('phone_number', models.CharField(max_length=25)),
                ('display_picture', models.ImageField(default='display_pictures/smily.jpg', upload_to='display_pictures')),
                ('district', models.CharField(max_length=25)),
                ('village', models.CharField(max_length=25)),
                ('stage', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('T', 'Member'), ('F', 'Non-Member'), ('P', 'Pending')], default='T', max_length=1, verbose_name='Membership Status')),
                ('card_id', models.IntegerField(verbose_name='Membership card id')),
                ('issue_date', models.DateTimeField(verbose_name='Date of issue of card')),
                ('expiry_date', models.DateTimeField(verbose_name='Date of expiry of card')),
            ],
        ),
    ]
