# Generated by Django 4.0.1 on 2023-07-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Member email')),
                ('title', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('display_picture', models.ImageField(default='display_pictures/smily.jpg', upload_to='display_pictures')),
                ('village', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('card_id', models.IntegerField(unique=True, verbose_name='Membership card id')),
                ('issue_date', models.DateTimeField(verbose_name='Date of issue of card')),
                ('expiry_date', models.DateTimeField(verbose_name='Date of expiry of card')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.stage')),
            ],
        ),
    ]
