# Generated by Django 4.0.1 on 2023-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='stage',
            field=models.CharField(max_length=25),
        ),
    ]
