# Generated by Django 4.2.3 on 2023-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("N", "Not Active")],
                default="T",
                max_length=1,
                null=True,
                verbose_name="Member Status",
            ),
        ),
    ]
