# Generated by Django 4.0.1 on 2023-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(default='dp', upload_to=''),
            preserve_default=False,
        ),
    ]
