# Generated by Django 4.0.1 on 2023-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(blank=True, default='images/smily.jpg', upload_to=''),
        ),
    ]
