# Generated by Django 4.0.1 on 2023-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_gender_alter_user_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(blank=True, default='display_pictures/smily.jpg', upload_to='display_pictures/'),
        ),
    ]
