# Generated by Django 4.0.1 on 2023-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(default='display_pictures/smily.jpg', upload_to='display_pictures'),
        ),
    ]
