# Generated by Django 4.0.1 on 2023-07-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_display_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_picture',
        ),
        migrations.AddField(
            model_name='member',
            name='display_picture',
            field=models.ImageField(default='display_pictures/smily.jpg', upload_to='display_pictures'),
        ),
    ]
