# Generated by Django 4.2.3 on 2023-08-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyinfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=50)),
                (
                    "display_picture",
                    models.ImageField(
                        default="display_pictures/smily.jpg",
                        upload_to="display_pictures",
                    ),
                ),
            ],
        ),
    ]
