# Generated by Django 4.0.1 on 2023-07-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAskedQuestions',
            new_name='FrequentlyAskedQuestion',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
